name: blendthink_lints
description: Lint rules for Flutter mobile apps by blendthink.
version: 0.0.1
homepage: https://github.com/blendthink/flutter-mobile-lints

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter_lints: ^1.0.4
