name: blendthink_lints
description: Recommended by blendthink set of lints for Flutter mobile apps to encourage good coding practices.
version: 0.0.4
homepage: https://github.com/blendthink/flutter-mobile-lints

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter_lints: ^1.0.4
