name: blendthink_lints
description: Recommended by blendthink set of lints for Flutter mobile apps to encourage good coding practices.
version: 3.0.0
homepage: https://github.com/blendthink/flutter-mobile-lints

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter_lints: ^2.0.1

dev_dependencies:
  grinder: ^0.9.2
