name: blendthink_lints
description: Recommended by blendthink set of lints for Flutter mobile apps to encourage good coding practices.
version: 2.0.0
homepage: https://github.com/blendthink/flutter-mobile-lints

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter_lints: ^2.0.1
